mex('remesh_botsch_mex.cpp',...
    '../../src/remesh_botsch.cpp',...
    '../../src/collapse_edges.cpp',...
    '../../src/equalize_valences.cpp',...
    '../../src/split_edges.cpp',...
    '../../src/split_edges_until_bound.cpp',...
    '../../src/tangential_relaxation.cpp',...   % '-I./libigl/include/',... %???
    '-I../../gptoolbox/mex/build/_deps/libigl-src/include',...
    '-I../../gptoolbox/mex/build/_deps/eigen-src','-V');
mex('per_face_prin_curvature_mex.cpp',...
    '-I../../gptoolbox/mex/build/_deps/libigl-src/include',...
    '-I../../gptoolbox/mex/build/_deps/eigen-src','-V');
mex('per_vertex_signed_prin_curvature_mex.cpp',...
    '-I../../gptoolbox/mex/build/_deps/libigl-src/include',...
    '-I../../gptoolbox/mex/build/_deps/eigen-src','-V');



